name: msds720
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.3
  - statsmodels>=0.14
  - scipy>=1.11
  - openpyxl>=3.1
  - jupyter
  - ipykernel
  - pip
  - pip:
    - python-dotenv>=1.0
    - kaggle>=2.0
